// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"lunar-commerce-fiber/internal/presenter/http/controller"
)

// Injectors from wire.go:

func NewWire() HTTPServiceInterface {
	configEnvConfigs := NewViper()
	app := NewFiber(configEnvConfigs)
	controllerController := controller.NewController()
	logger := NewLogger(configEnvConfigs)
	httpServiceInterface := NewListenApp(app, controllerController, configEnvConfigs, logger)
	return httpServiceInterface
}
