CREATE TABLE IF NOT EXISTS roles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  updatedAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  deletedAt TIMESTAMP,
  CONSTRAINT UQ_roles_name UNIQUE (name)
);