START TRANSACTION;

CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenantId BIGINT UNSIGNED NOT NULL,
  productId BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  statusId BIGINT UNSIGNED,
  createdAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  updatedAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  deletedAt TIMESTAMP,
  CONSTRAINT FK_product_images_tenants_id
  FOREIGN KEY (tenantId) REFERENCES tenants(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_product_images_product_id
  FOREIGN KEY (productId) REFERENCES products(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_product_images_status_id
  FOREIGN KEY (statusId) REFERENCES statuses(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

COMMIT;