START TRANSACTION;

CREATE TABLE IF NOT EXISTS level_tenants (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  level VARCHAR(255),
  createdAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  updatedAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  deletedAt TIMESTAMP
);

COMMIT;