START TRANSACTION;

CREATE TABLE IF NOT EXISTS memberships (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenantId BIGINT UNSIGNED NOT NULL,
  userId BIGINT UNSIGNED,
  roleId BIGINT UNSIGNED NOT NULL,
  statusId BIGINT UNSIGNED NOT NULL,
  hash VARCHAR(255),
  createdAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  updatedAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  deletedAt TIMESTAMP,
  CONSTRAINT FK_memberships_roles_id
  FOREIGN KEY (roleId) REFERENCES roles(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_memberships_statuses_id
  FOREIGN KEY (statusId) REFERENCES statuses(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_memberships_tenants_id
  FOREIGN KEY (tenantId) REFERENCES tenants(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_memberships_users_id
  FOREIGN KEY (userId) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  INDEX IDX_memberships_hash (hash)
);

COMMIT;