START TRANSACTION;

CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  totalProduct INT NOT NULL DEFAULT 0,
  status BOOLEAN NOT NULL DEFAULT false,
  createdAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  updatedAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  deletedAt TIMESTAMP,
  CONSTRAINT UQ_tenants_name UNIQUE (name)
);

COMMIT;
