START TRANSACTION;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  totalStock INT NOT NULL DEFAULT 0,
  totalSold INT NOT NULL DEFAULT 0,
  price INT NOT NULL DEFAULT 0,
  description LONGTEXT,
  specification LONGTEXT,
  tenantId BIGINT UNSIGNED NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  updatedAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  deletedAt TIMESTAMP,
  CONSTRAINT FK_products_tenants_id
  FOREIGN KEY (tenantId) REFERENCES tenants(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

COMMIT;