START TRANSACTION;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255),
  password VARCHAR(255),
  name VARCHAR(255),
  hash VARCHAR(255),
  avatar VARCHAR(255),
  roleId BIGINT UNSIGNED NOT NULL,
  statusId BIGINT UNSIGNED,
  createdAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  updatedAt TIMESTAMP NOT NULL DEFAULT (CURRENT_DATE),
  deletedAt TIMESTAMP,
  CONSTRAINT UQ_users_email UNIQUE (email),
  CONSTRAINT FK_users_roles_id
  FOREIGN KEY (roleId) REFERENCES roles(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_users_statuses_id
  FOREIGN KEY (statusId) REFERENCES statuses(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  INDEX IDX_users_hash (hash)
);

COMMIT;